# # General Settings
# name: Yibo Wang
# job_title: Current Graduate at USC
# email: quentin0307@hotmail.com
# description:
# avatar: /assets/images/IMG_2039.jpeg
# favicon: /favicon.ico
# twitter_handler: your_handler
# analytics_code: UA-XXXXXXX-2
# disqus: your_disqus_site

# # Social Accounts
# social_networks:
# -  { name: facebook, url: 'http://facebook.com' }
# -  { name: twitter, url: 'https://twitter.com/loneran2' }
# -  { name: instagram, url: '' }
# -  { name: google-plus, url: '' }
# -  { name: linkedin, url: 'http://www.linkedin.com/in/yibo--wang' }
# -  { name: skype, url: '' }
# -  { name: github, url: 'http://github.com/LoneRan' }
# -  { name: codepen, url: '' }
# -  { name: stack-overflow, url: '' }
# -  { name: dribbble, url: '' }
# -  { name: behance, url: '' }
# -  { name: pinterest, url: '' }
# -  { name: tumblr, url: '' }
# -  { name: youtube, url: 'https://www.youtube.com/channel/UCHDgQOG6ThWuNztH-vBc_8w?view_as=subscriber' }
# -  { name: vimeo, url: '' }
# -  { name: vine, url: '' }
# -  { name: 500px, url: '' }
# -  { name: flickr, url: '' }
# -  { name: spotify, url: '' }
# -  { name: steam, url: '' }
# -  { name: wordpress, url: '' }
# -  { name: xing, url: '' }
# -  { name: bitcoin, url: '' }
# -  { name: pocket, url: '' }
# -  { name: applemusic, url: '' }

# # Modules Settings
# show_categories: 1
# show_tags: 1
# show_email: 1
# show_rss: 1
# show_comments: 1
# show_menu: 1
# fixed_sidebar: 1

# # Defaults
# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       comments: "true"

# # Serving
# url: "https://loneran.github.io"
# baseurl: ""

# # Includes
# include: ["_pages"]

# # Outputting
# permalink: /:categories/:title.html
# category_dir: categories

# # Pagination
# paginate: 10
# paginate_path: "/page:num/"

# # Conversion
# markdown: kramdown
# excerpt_separator: <!--more-->

# # Assets Settings
# sass:
#   sass_dir: assets/partials
#   style: compressed

# General Settings
name: Yibo Wang
job_title: Software Developer Intern @iSmileTechnologies. Currently graduate @USC
email: yibo.ivan.wang@gmail.com
description: I enjoy coding, especially the one with a neat style and high performance. Interested in both front-end and back-end development. 
avatar: /assets/images/IMG_2039.jpeg
favicon: /favicon.ico
twitter_handler: your_handler
analytics_code: UA-XXXXXXX-2
disqus: your_disqus_site

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'http://twitter.com/loneran2' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'http://www.linkedin.com/in/yibo--wang' }
-  { name: skype, url: '' }
-  { name: github, url: 'http://github.com/LoneRan' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: "http://aboutyibo.com"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed
